const ENDPOINTS={ready:"/ready",combined:"/v1/combined-inspections",history:"/v1/combined-inspections?limit=8&offset=0"};
const q=(s)=>document.querySelector(s);
const el={runtimeChip:q("#runtime-chip"),runtimeLabel:q("#runtime-label"),imageInput:q("#image-input"),dropZone:q("#drop-zone"),dropPlaceholder:q("#drop-placeholder"),previewImage:q("#preview-image"),boxLayer:q("#box-layer"),fileMeta:q("#file-meta"),inspectButton:q("#inspect-button"),inspectLabel:q("#inspect-label"),inspectSpinner:q("#inspect-spinner"),resetButton:q("#reset-button"),decisionPill:q("#decision-pill"),emptyResult:q("#empty-result"),resultContent:q("#result-content"),errorBox:q("#error-box"),decisionDisposition:q("#decision-disposition"),decisionReasonCode:q("#decision-reason-code"),decisionReason:q("#decision-reason"),patchcorePrediction:q("#patchcore-prediction"),patchcoreScore:q("#patchcore-score"),patchcoreThreshold:q("#patchcore-threshold"),patchcoreDevice:q("#patchcore-device"),yoloCount:q("#yolo-count"),yoloClasses:q("#yolo-classes"),yoloInference:q("#yolo-inference"),yoloDevice:q("#yolo-device"),defectSummary:q("#defect-summary"),defectList:q("#defect-list"),combinedId:q("#combined-id"),imageSha:q("#image-sha"),patchcoreMs:q("#patchcore-ms"),orchestrationMs:q("#orchestration-ms"),refreshHistory:q("#refresh-history"),historyList:q("#history-list")};
let selectedFile=null,previewUrl=null,latest=null;
const num=(v,d=3)=>Number.isFinite(v)?Number(v).toFixed(d):"—";
const stateClass=(v)=>String(v||"").toLowerCase()==="accept"?"accept":String(v||"").toLowerCase()==="reject"?"reject":"idle";
async function readiness(){try{const r=await fetch(ENDPOINTS.ready,{cache:"no-store"});if(!r.ok)throw new Error();const x=await r.json();if(x.status!=="ready")throw new Error();el.runtimeChip.classList.add("ready");el.runtimeLabel.textContent=`${String(x.device).toUpperCase()} · ${x.model_name}`}catch(e){el.runtimeChip.classList.add("error");el.runtimeLabel.textContent="API unavailable";console.error(e)}}
function clearBoxes(){el.boxLayer.replaceChildren()}
function imageRect(){if(!el.previewImage.naturalWidth)return null;const w=el.dropZone.clientWidth,h=el.dropZone.clientHeight,s=Math.min(w/el.previewImage.naturalWidth,h/el.previewImage.naturalHeight),rw=el.previewImage.naturalWidth*s,rh=el.previewImage.naturalHeight*s;return{left:(w-rw)/2,top:(h-rh)/2,width:rw,height:rh}}
function renderBoxes(payload){clearBoxes();const rect=imageRect(),image=payload?.image,instances=payload?.known_defects?.instances;if(!rect||!image||!Array.isArray(instances))return;for(const instance of instances){const b=instance.box,node=document.createElement("div");node.className="box";node.style.left=`${rect.left+b.x_min/image.width*rect.width}px`;node.style.top=`${rect.top+b.y_min/image.height*rect.height}px`;node.style.width=`${(b.x_max-b.x_min)/image.width*rect.width}px`;node.style.height=`${(b.y_max-b.y_min)/image.height*rect.height}px`;const label=document.createElement("label");label.textContent=`${instance.class_name} ${(instance.confidence*100).toFixed(1)}%`;node.append(label);el.boxLayer.append(node)}}
function resetResult(){el.decisionPill.textContent="WAITING";el.decisionPill.className="pill idle";el.emptyResult.hidden=false;el.resultContent.hidden=true}
function setFile(file){if(!file)return;if(!["image/jpeg","image/png"].includes(file.type)){el.errorBox.textContent="Please choose a JPEG or PNG image.";el.errorBox.hidden=false;return}selectedFile=file;latest=null;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);el.previewImage.src=previewUrl;el.previewImage.hidden=false;el.dropPlaceholder.hidden=true;el.fileMeta.textContent=`${file.name} · ${(file.size/1024).toFixed(1)} KB`;el.inspectButton.disabled=false;el.errorBox.hidden=true;clearBoxes();resetResult()}
function resetAll(){selectedFile=null;latest=null;el.imageInput.value="";el.previewImage.removeAttribute("src");el.previewImage.hidden=true;el.dropPlaceholder.hidden=false;el.fileMeta.textContent="No image selected";el.inspectButton.disabled=true;el.errorBox.hidden=true;clearBoxes();resetResult();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null}
function renderDefects(instances){el.defectList.replaceChildren();if(!instances.length){const x=document.createElement("div");x.className="empty small";x.textContent="No known-defect instances detected.";el.defectList.append(x);return}instances.forEach((instance,i)=>{const row=document.createElement("div");row.className="defect-row";const values=[`#${i+1} · ${instance.class_name}`,`${(instance.confidence*100).toFixed(1)}% conf`,`${(instance.mask.area_ratio*100).toFixed(2)}% mask`,`${Math.round(instance.box.x_min)},${Math.round(instance.box.y_min)} → ${Math.round(instance.box.x_max)},${Math.round(instance.box.y_max)}`];values.forEach((v,j)=>{const c=document.createElement(j===0?"b":"span");c.textContent=v;row.append(c)});el.defectList.append(row)})}
function render(payload){latest=payload;const d=payload.decision,p=payload.patchcore,k=payload.known_defects,instances=Array.isArray(k.instances)?k.instances:[],disp=String(d.disposition).toUpperCase();el.emptyResult.hidden=true;el.resultContent.hidden=false;el.decisionPill.textContent=disp;el.decisionPill.className=`pill ${stateClass(d.disposition)}`;el.decisionDisposition.textContent=disp;el.decisionReasonCode.textContent=d.reason_code;el.decisionReason.textContent=d.reason;el.patchcorePrediction.textContent=p.is_anomaly?"ANOMALY":"NORMAL";el.patchcoreScore.textContent=num(p.anomaly_score,4);el.patchcoreThreshold.textContent=`${p.comparison_operator} ${num(p.threshold,4)}`;el.patchcoreDevice.textContent=String(p.device).toUpperCase();el.yoloCount.textContent=String(instances.length);el.yoloClasses.textContent=[...new Set(instances.map(x=>x.class_name))].join(", ")||"None";el.yoloInference.textContent=`${num(payload.timings.yolo_inference_ms,2)} ms`;el.yoloDevice.textContent=String(k.model.device).toUpperCase();el.defectSummary.textContent=`${instances.length} instance${instances.length===1?"":"s"}`;renderDefects(instances);el.combinedId.textContent=payload.combined_inspection_id;el.imageSha.textContent=payload.image.sha256;el.patchcoreMs.textContent=`${num(payload.timings.patchcore_inference_ms,2)} ms`;el.orchestrationMs.textContent=`${num(payload.timings.orchestration_ms,2)} ms`;renderBoxes(payload)}
async function runInspection(){if(!selectedFile)return;el.inspectButton.disabled=true;el.inspectLabel.textContent="Running GPU inspection…";el.inspectSpinner.hidden=false;try{const body=new FormData();body.append("image",selectedFile);const r=await fetch(ENDPOINTS.combined,{method:"POST",body,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Inspection failed with HTTP ${r.status}`);render(await r.json());await loadHistory()}catch(e){el.errorBox.textContent=e.message||"Inspection failed.";el.errorBox.hidden=false}finally{el.inspectButton.disabled=!selectedFile;el.inspectLabel.textContent="Run combined inspection";el.inspectSpinner.hidden=true}}
function history(payload){el.historyList.replaceChildren();const items=Array.isArray(payload?.items)?payload.items:[];if(!items.length){el.historyList.innerHTML='<div class="empty small">No persisted combined inspections yet.</div>';return}for(const item of items){const row=document.createElement("div");row.className="history-row";const values=[new Date(item.created_at).toLocaleString(),item.combined_inspection_id.slice(0,8),`PatchCore · ${item.patchcore_prediction}`,`YOLO · ${item.known_defect_instance_count}`,`${item.disposition} · ${item.reason_code}`];values.forEach((v,i)=>{const c=document.createElement(i===1||i===4?"strong":"span");if(i===4)c.className=stateClass(item.disposition);c.textContent=v;row.append(c)});el.historyList.append(row)}}
async function loadHistory(){try{const r=await fetch(ENDPOINTS.history,{cache:"no-store"});if(!r.ok)throw new Error();history(await r.json())}catch(e){el.historyList.innerHTML='<div class="empty small">Recent history is temporarily unavailable.</div>';console.error(e)}}
el.imageInput.addEventListener("change",()=>setFile(el.imageInput.files?.[0]||null));el.dropZone.addEventListener("dragover",e=>{e.preventDefault();el.dropZone.classList.add("dragging")});el.dropZone.addEventListener("dragleave",()=>el.dropZone.classList.remove("dragging"));el.dropZone.addEventListener("drop",e=>{e.preventDefault();el.dropZone.classList.remove("dragging");setFile(e.dataTransfer?.files?.[0]||null)});el.inspectButton.addEventListener("click",runInspection);el.resetButton.addEventListener("click",resetAll);el.refreshHistory.addEventListener("click",loadHistory);el.previewImage.addEventListener("load",()=>{if(latest)renderBoxes(latest)});window.addEventListener("resize",()=>{if(latest)renderBoxes(latest)});readiness();loadHistory();
